### ISSUE TITLE
1.16 plz

### ISSUE THREAD

**Issue by TowardtheStars** [ustc-zzzz/WaterSprayer#2]
I really like this mod. Please make a version for 1.16.5.
做个 1.16.5 的版本呗！（滑稽）

**Comment by ustc-zzzz** [comment]
https://github.com/ustc-zzzz/WaterSprayer/releases/tag/v1.1.0
记得使用 https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force 作为前置。
